### ISSUE TITLE
git2consul failed to pull files from repo

### ISSUE THREAD

**Issue by sudo-p** [ryanbreen/git2consul_data#3]
C:\Users\prana\Downloads\demo>**git2consul --config-file git2consul.json**
{"name":"git2consul","hostname":"lenovoLegion","pid":19444,"level":30,"msg":"Adding git2consul.json to KV git2consul/config as: \n{\r\n  \"version\": \"1.0\",\r\n  \"repos\" : [{\r\n    \"name\" : \"sample_configuration\",\r\n    \"url\" : \"git@github.com:ryanbreen/git2consul_data.git\",\r\n    \"branches\" : [\"dev\"],\r\n    \"hooks\": [{\r\n      \"type\" : \"polling\",\r\n      \"interval\" : \"1\"\r\n    }]\r\n  }]\r\n}","time":"2020-07-05T04:02:16.073Z","v":0}
{"name":"git2consul","hostname":"lenovoLegion","pid":19444,"level":30,"msg":"git2consul is running","time":"2020-07-05T04:02:16.259Z","v":0}
{"name":"git2consul","hostname":"lenovoLegion","pid":19444,"level":50,"msg":"**Failed to create repos due to TypeError: process.getuid is not a function**\n    at Object.module.exports.validate_writeable_directory (C:\\Users\\prana\\AppData\\Roaming\\npm\\node_modules\\git2consul\\lib\\utils.js:15:29)\n    at new Repo (C:\\Users\\prana\\AppData\\Roaming\\npm\\node_modules\\git2consul\\lib\\git\\repo.js:46:9)\n    at C:\\Users\\prana\\AppData\\Roaming\\npm\\node_modules\\git2consul\\lib\\git\\index.js:109:43\n    at Array.forEach (<anonymous>)\n    at C:\\Users\\prana\\AppData\\Roaming\\npm\\node_modules\\git2consul\\lib\\git\\index.js:99:18\n    at C:\\Users\\prana\\AppData\\Roaming\\npm\\node_modules\\git2consul\\node_modules\\mkdirp\\index.js:47:26\n    at FSReqCallback.oncomplete (fs.js:167:5)","time":"2020-07-05T04:02:16.264Z","v":0}

**Comment by sudo-p** [comment]
I was able to fix this issue by making a change to `lib/utils.js` inside git2consul installation directory

# changed

`var can_write =  ((process.getuid() === stat.uid) && (stat.mode & 00200)) || // User is owner and owner can write.
                  ((process.getgid() === stat.gid) && (stat.mode & 00020)) || // User is in group and group can write.
                  ((stat.mode & 00002)); // Anyone can write`

# to

`  var can_write = (!process.getuid) || 
                  ((process.getuid() === stat.uid) && (stat.mode & 00200)) || // User is owner and owner can write.
                  ((process.getgid() === stat.gid) && (stat.mode & 00020)) || // User is in group and group can write.
                  ((stat.mode & 00002)); // Anyone can write.`
